# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'notepad_ios' do
  use_frameworks!
  # 忽略引入库的所有警告
  inhibit_all_warnings!
  pod 'Moya'
  pod 'HandyJSON', '~> 5.0.0-beta.1'
  pod 'SwiftyJSON'
end



